# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-26 15:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import elvis.models.attachment
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, max_length=512, null=True, upload_to=elvis.models.attachment.upload_path)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('public', models.NullBooleanField()),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('curators', models.ManyToManyField(blank=True, related_name='curates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'collections',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Composer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('birth_date', models.IntegerField(blank=True, null=True)),
                ('death_date', models.IntegerField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.ManyToManyField(blank=True, related_name='downloads', to='elvis.Attachment')),
                ('collection_collections', models.ManyToManyField(blank=True, related_name='user_downloads', to='elvis.Collection')),
                ('collection_composers', models.ManyToManyField(blank=True, related_name='user_downloads', to='elvis.Composer')),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='InstrumentVoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('number_of_voices', models.IntegerField(blank=True, null=True)),
                ('religiosity', models.CharField(default='Unknown', max_length=50)),
                ('vocalization', models.CharField(default='Unknown', max_length=50)),
                ('composition_start_date', models.IntegerField(blank=True, null=True)),
                ('composition_end_date', models.IntegerField(blank=True, null=True)),
                ('position', models.IntegerField(blank=True, null=True)),
                ('parent_cart_id', models.CharField(max_length=50, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(blank=True, related_name='movements', to='elvis.Attachment')),
                ('collections', models.ManyToManyField(blank=True, related_name='movements', to='elvis.Collection')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='elvis.Composer')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='movements', to='elvis.Genre')),
                ('instruments_voices', models.ManyToManyField(blank=True, related_name='movements', to='elvis.InstrumentVoice')),
                ('languages', models.ManyToManyField(blank=True, related_name='movements', to='elvis.Language')),
                ('locations', models.ManyToManyField(blank=True, related_name='movements', to='elvis.Location')),
            ],
            options={
                'ordering': ['position', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Piece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('number_of_voices', models.IntegerField(blank=True, null=True)),
                ('religiosity', models.CharField(default='Unknown', max_length=50)),
                ('vocalization', models.CharField(default='Unknown', max_length=50)),
                ('composition_start_date', models.IntegerField(blank=True, null=True)),
                ('composition_end_date', models.IntegerField(blank=True, null=True)),
                ('hidden', models.BooleanField(default=False)),
                ('attachments', models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Attachment')),
                ('collections', models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Collection')),
                ('composer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='elvis.Composer')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('genres', models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Genre')),
                ('instruments_voices', models.ManyToManyField(blank=True, related_name='pieces', to='elvis.InstrumentVoice')),
                ('languages', models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Language')),
                ('locations', models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Location')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='NOTITLE_ERROR', max_length=255)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='piece',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Source'),
        ),
        migrations.AddField(
            model_name='piece',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Tag'),
        ),
        migrations.AddField(
            model_name='movement',
            name='piece',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='elvis.Piece'),
        ),
        migrations.AddField(
            model_name='movement',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='movements', to='elvis.Source'),
        ),
        migrations.AddField(
            model_name='movement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movements', to='elvis.Tag'),
        ),
        migrations.AddField(
            model_name='download',
            name='collection_movements',
            field=models.ManyToManyField(blank=True, related_name='user_downloads', to='elvis.Movement'),
        ),
        migrations.AddField(
            model_name='download',
            name='collection_pieces',
            field=models.ManyToManyField(blank=True, related_name='user_downloads', to='elvis.Piece'),
        ),
        migrations.AddField(
            model_name='download',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('elvis.location',),
        ),
    ]
