# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-01-27 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='original_file_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
