# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models


def fill_new_field(apps, schema_editor):
    Movement = apps.get_model("elvis", "Movement")
    print("Saving parent_cart_id's for movements.")
    i = 0
    total = str(Movement.objects.count())
    msg = "Applying to movement {}/" + total
    for m in Movement.objects.all():
        print(msg.format(str(i)))
        i += 1
        p = m.piece
        if p and not m.parent_cart_id:
            m.parent_cart_id = "P-" + str(p.uuid)
            m.save(commit_solr=False)


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0010_auto_20160205_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='parent_cart_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.RunPython(fill_new_field),
    ]
