# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-05 18:50
from __future__ import unicode_literals

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0010_auto_20160205_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='parent_cart_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]

"""I tried to include these functions in the automatic migration,
but they failed. So run these two functions in a django shell after
migrating in order to populate the new fields and refactor how attachments
are referenced.

In IPython (manage.py shell_plus) you can type '%cpaste' to easily copy
these in.
"""
