# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 21:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elvis', '0011_movement_parent_cart_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderates', to=settings.AUTH_USER_MODEL),
        ),
    ]
