# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-12 21:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('elvis', '0012_collection_moderators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='moderators',
        ),
        migrations.AddField(
            model_name='collection',
            name='curators',
            field=models.ManyToManyField(blank=True, related_name='curates', to=settings.AUTH_USER_MODEL),
        ),
    ]
