# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-13 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0013_auto_20160212_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='movement',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='piece',
            name='hidden',
            field=models.BooleanField(default=False),
        ),
    ]
