# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0013_auto_20160212_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Attachment'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Collection'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movement', to='elvis.Composer'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Genre'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='instruments_voices',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.InstrumentVoice'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Language'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Location'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Source'),
        ),
        migrations.AlterField(
            model_name='movement',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='movement', to='elvis.Tag'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Attachment'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Collection'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='composer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='piece', to='elvis.Composer'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Genre'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='instruments_voices',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.InstrumentVoice'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Language'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Location'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='sources',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Source'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='piece', to='elvis.Tag'),
        ),
    ]
