# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-04 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0014_auto_20160304_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movement',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='movements', to='elvis.Collection'),
        ),
        migrations.AlterField(
            model_name='piece',
            name='collections',
            field=models.ManyToManyField(blank=True, related_name='pieces', to='elvis.Collection'),
        ),
    ]
