# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elvis', '0014_auto_20160613_1734'),
        ('elvis', '0002_auto_20160623_1910'),
    ]

    operations = [
    ]
